import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Server Action',
  description: 'Generated by Mavene',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
